language: node_js

node_js:
  - stable
  - lts/*

cache:
  directories:
    - node_modules

notifications:
  email: true

branches:
  only:
    - master

install:
  - npm install

jobs:
  include:
    - stage: release
      script:
        - npm run build
        - npm run lint
        - npm run test
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run semantic-release
