---
blank_issues_enabled: false
contact_links:
  - name: Boilerplate Lib Rollup
    url: https://github.com/teixeiravictor/boilerplate-lib/discussions
    about: Please ask and answer questions here.